[versions]
# lib
kotlin = "2.3.0"
coroutines = "1.10.2"
binary-compatibility-validator = "0.18.1"

# examples
agp = "8.13.2"
android-minSdk = "28"
android-compileSdk = "36"
androidx-activity-compose = "1.12.2"
androidx-compose-bom = "2026.01.00"
androidx-material3 = "1.4.0"
espresso = "3.7.0"
junit-ktx = "1.3.0"
maven-publish-plugin = "0.36.0"
kover = "0.9.4"
ktlint = "14.0.1"
androidx-ui-test-junit4 = "1.10.1"

[libraries]
# lib
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# examples
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material = { module = "androidx.compose.material3:material3", version.ref = "androidx-material3" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junit-ktx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish-plugin" }
