name: "build"

on: push

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version-file: .java-version
      - name: "lint"
        run: ./gradlew lint ktlintCheck

  test:
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version-file: .java-version
      - name: "Test"
        run: ./gradlew test

  check_coverage:
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version-file: .java-version
      - name: "Check if coverage is satisfied"
        run: ./gradlew koverVerify

  api_validation:
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version-file: .java-version
      - name: "Validates the Api"
        run: ./gradlew apiCheck

  assemble:
    needs: [lint, test, check_coverage]
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version-file: .java-version
      - name: "Assemble"
        run: ./gradlew assemble

  upload_coverage:
    needs: [assemble]
    runs-on: macos-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version-file: .java-version
      - name: "Create coverage reports"
        run: ./gradlew koverXmlReport
      - name: "Upload coverage to codecov"
        uses: codecov/codecov-action@v5.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./control-core/build/reports/kover/report.xml
          fail_ci_if_error: true
